// src/server/constants/feature-request.js
export const FEATURE_REQUEST_STATUS = {
  PENDING: 'pending',
  APPROVED: 'approved',
  IN_PROGRESS: 'in_progress',
  DONE: 'done',
  REJECTED: 'rejected',
};

export const FEATURE_REQUEST_STATUS_LIST = [
  FEATURE_REQUEST_STATUS.PENDING,
  FEATURE_REQUEST_STATUS.APPROVED,
  FEATURE_REQUEST_STATUS.IN_PROGRESS,
  FEATURE_REQUEST_STATUS.DONE,
  FEATURE_REQUEST_STATUS.REJECTED,
];

export const FEATURE_REQUEST_STATUS_LABELS = {
  [FEATURE_REQUEST_STATUS.PENDING]: 'Pending',
  [FEATURE_REQUEST_STATUS.APPROVED]: 'Approved',
  [FEATURE_REQUEST_STATUS.IN_PROGRESS]: 'In Progress',
  [FEATURE_REQUEST_STATUS.DONE]: 'Done',
  [FEATURE_REQUEST_STATUS.REJECTED]: 'Rejected',
};

export const API_ENDPOINTS = {
  APPS: 'apps',
  FEATURE_REQUESTS: 'feature-requests',
};

export const VALIDATION = {
  API_KEY_LENGTH: 32,
  MAX_TITLE_LENGTH: 200,
  MAX_DESCRIPTION_LENGTH: 5000,
  MAX_COMMENT_LENGTH: 2000,
  MAX_IMAGES_PER_REQUEST: 5,
  MAX_IMAGES_PER_COMMENT: 3,
};
